#!/usr/bin/env node

'use strict';

var fs = require('fs');
var path = require('path');
var adify = require('../src/transforms/adify').adify;

var inFile = path.join(__dirname, '../src/erp.ad.js');
var outFile = path.join(__dirname, '../src/erp.js');

var code = fs.readFileSync(inFile, 'utf8');
fs.writeFileSync(outFile, adify(code));
