#!/usr/bin/env node

'use strict';

// Require this version so that we don't need to run the build in
// order to build the docs.
var dists = require('../src/dists.ad.js');
var _ = require('underscore');

function getMetaData() {
  return _.chain(dists)
    .pairs() // pair[0] = key, pair[1] = value
    .filter(function(pair) {
      var dist = pair[1];
      return dists.isDist(dist.prototype);
    })
    .sortBy(function(pair) { return pair[0]; })
    .map(function(pair) { return pair[1]; })
    .map(function(dist) {
      return dist.prototype.meta;
    })
    .filter(function(meta) { return !meta.internal; })
    .value();
}

function makeTemplates(obj) {
  return _.mapObject(obj, _.template);
}

var t = makeTemplates({
  func:            '.. js:function:: <%= name %>({<%= args %>})\n',
  arg:             '<%= name %>: ...',
  param:           '  * <%= name %>: <%= desc %>',
  paramWithDomain: '  * <%= name %>: <%= desc %> *(<%= domain %>)*',
  desc:            '  <%= desc %>\n',
  wikiEntry:     '  `Wikipedia entry <https://en.wikipedia.org/wiki/<%= page %>>`__\n'
});

function formatDomain(interval) {
  if (interval.a === -Infinity) {
    return '<' + interval.b;
  } else if (interval.b === Infinity) {
    return '>' + interval.a;
  } else {
    return 'in [' + [interval.a, interval.b] + ']';
  }
}

var body = getMetaData().map(function(meta) {

  var out = [];

  out.push(t.func({
    name: meta.name,
    args: meta.params.map(t.arg).join(', ')
  }));

  meta.params.forEach(function(param) {
    var p = _.extendOwn({desc: ''}, param);
    if (p.domain) {
      p.domain = formatDomain(p.domain);
    }
    out.push((param.domain ? t.paramWithDomain : t.param)(p));
  });

  out.push('');

  if (meta.desc) {
    out.push(t.desc(meta));
  }

  if (meta.wikipedia) {
    var page = (meta.wikipedia === true) ? meta.name + '_distribution' : meta.wikipedia;
    out.push(t.wikiEntry({page: page}));
  }

  return out;

});

console.log(_.flatten(body).join('\n'));
