#!/usr/bin/env node

'use strict';

// Require this version so that we don't need to run the build in
// order to build the docs.
var dists = require('../src/dists.ad.js');
var _ = require('underscore');

function makeTemplates(obj) {
  return _.mapObject(obj, _.template);
}

var t = makeTemplates({
  func:          '.. js:function:: <%= name %>({<%= args %>})\n',
  arg:           '<%= name %>: ...',
  param:         '  * <%= name %>: <%= desc %>',
  paramWithType: '  * <%= name %>: <%= desc %> *(<%= type.desc %>)*',
  desc:          '  <%= desc %>\n',
  wikiEntry:     '  `Wikipedia entry <https://en.wikipedia.org/wiki/<%= page %>>`__\n'
});

var metadata = dists.metadata().filter(function(meta) { return !meta.nodoc; });

var body = metadata.map(function(meta) {

  var out = [];

  out.push(t.func({
    name: meta.name,
    args: meta.params.map(t.arg).join(', ')
  }));

  meta.params.forEach(function(param) {
    var p = _.extendOwn({desc: ''}, param);
    out.push((param.type ? t.paramWithType : t.param)(p));
  });

  out.push('');

  if (meta.desc) {
    out.push(t.desc(meta));
  }

  if (meta.wikipedia) {
    var page = (meta.wikipedia === true) ? meta.name + '_distribution' : meta.wikipedia;
    out.push(t.wikiEntry({page: page}));
  }

  return out;

});

console.log(_.flatten(body).join('\n'));
