#!/usr/bin/env node

'use strict';

var fs = require('fs');
var path = require('path');
var adscorers = require('../src/transforms/adscorers').adscorers;

var inFile = path.join(__dirname, '../src/erp.ad.js');
var outFile = path.join(__dirname, '../src/erp.js');

var code = fs.readFileSync(inFile, 'utf8');
fs.writeFileSync(outFile, adscorers(code));
